# Communication

*Effective teamwork begins and ends with communication*

    Mike Krzyzewski (former US basketball coach) 

## Internal communications

Zulip and email are our main channels for written communication within the team. MS Teams is our primary channel for online meetings. During regular work hours it is recommended to be logged in to Zulip as well as MS Teams. We recommend using the MS Teams desktop app for optimal use. Please note: The Zulip desktop app cannot be downloaded and installed on Charité/BIH managed computers. 

Some tasks, such as writing a manuscript during one of our CAMARADES writing retreats, require concentration and minimizing disctractions (e.g., by checking emails or messages on Zulip or MS Teams). Feel free to set your status on Teams accordingly by indicating that you are 'busy' or 'away from the computer'. You do not indicate this specifically on Zulip, as it will automatically show you as 'idle' when you are not active. However, if you wish to do so, you can select an icon which best represents your current status and update the corresponding status message. 

## External communications 

Aside from emails for regular external communications, we are using LinkedIn (via the COReS profile) and Zulip.

* For content to be posted via LinkedIn, please reach out to Friederike.
* On Zulip, you can use different streams to reach people. Use the SR_Methods stream to post and discuss methodological questions related to systematic reviews, while you can use the Education stream to share workshops, eLearning, training opportunities and oder educational offers. Announce events, meetings, and conferences that might be of interest to a wider audience va the General stream (topic: Events). 

## Group and project meetings

Within the CAMARADES team, individual project meetings take place at specific times:
* The systematic review and meta-analysis methods meeting is every Wednesday at 15:00pm 

* The COReS project meeting is every week on Wednesday at 9:30am  

* The INFORM-Stroke project meeting is every Wednesday starting right after the SR-MA methods meeting of 15:00pm

Further, overarching group meetings within CAMARADES Berlin and the broader CAMARADES community take place:

**Every Wednesday @ 08:30am or 09:00 am (alternating between weeks): CAMARADES Berlin Strategy Meeting** 

* Alternating between short (30') and long (60') meetings. Long meetings start at the earlier time
* Team members share updates, potential problems, work distributions, etc.. The full agenda of each strategy meeting can be found in the CAMARADES Berlin Admin notebook on Sharepoint.
* A specific overarching topic (such as 'engagement and dissemination strategy' or 'education formats') will be discussed during the longer group meetings 

**Every Tuesday @ 10:30am or 3:00pm (alternating between weeks): CAMARADES Global Tuesday Meeting**

* The idea of the CAMARADES Global meeting is to foster collaboration among CAMARADES members from seven national coordinating centers and with others involved in preclinical systematic review and meta-analysis. The meetings provide an opportunity to ask methodological questions or receive input from peers. 
* The meetings are scheduled as one of two formats:  
  + General update meetings, where everyone is invited to share recent news or ask for feedback on particular issues, or 
  + Presentation meetings, where a member will make a short presentation followed by discussion.
* Slides and short summaries of the presentation meetings will be shared via Zulip (stream: CAMARADES Global, topic: Global Meetings)


## Mailing lists

Make sure that you are signed up for the CAMARADES Global maling list. If you are not, please contact Sarah and ask to be added to the list. 


