# Key resources
## BIH/QUEST administration
Everything you need to know about different administrative procedures like requesting sick days or annual leave, working hours, the infamous PEP system and many more QUEST level things can be found in the QUEST [wiki](https://quest-wiki.premier.charite.de/index.php/Category:QUEST_Office_Admin). We are constantly adding new info to the wiki (thanks to Friederike's initiative of a monthly Wiki happy hour), so if something you think is relevant is missing you are more than welcome to add it yourself. If the answer you are looking for is not on the wiki, you can email Ruth or Gabriela (QUEST admin team) to ask for clarification. 

## Common CAMARADES resources and acronyms
To familiarize yourself with our ongoing projects you can check our [research group's page](https://quest-wiki.premier.charite.de/index.php/Research_Group_McCann) on the QUEST wiki. There you will find the acronyms we use for each project (which you will be hearing a lot in our meetings), which team member(s) work on which project, and monthly project updates. Other than that, here is a list of common tools/software we use you should get familiar with and create user accounts for where necessary.

- SR&MA: systematic review and meta-analysis
- ASySD: Automated deduplicator tool for removing duplicates across systematic searches, developed in-house.
- SOLES: Systematic Online Living Evidence Summaries, a pipeline and dashboard summarising the latest research findings in a given research area. We have developed many SOLES for different evidence domains (e.g. Cancer-SOLES, Stroke-SOLES)
- [SyRF](https://syrf.org.uk/): Our in-house systematic review platform. We use it for screening for inclusion and extracting information and data from publications.
- GitHub: Central platform for code sharing and collaboration on various projects.
- [SharePoint](https://charitede.sharepoint.com/sites/StrokeCoMorb/Shared%20Documents/Forms/AllItems.aspx): We use sharepoint to manage our files and folders. This is accessible via Teams by going to the “Files” tab or from the browser. You will find all the necessary files there, and you should upload all the files you work on there regularly (when doing so, please adhere to file naming conventions described in chapter X Data Management). 
- Teams: We use Microsoft Teams for onlinmeetings and file-management. You will get an invite to join on your first day.
- [Zulip](https://zulip.com/apps/): An open-source messaging app for better team communication and collaboration. We use this for our daily internal communication but also to communicate with the wider COReS network (check what COReS is about on wiki!). You will get an invite to join on your first day.

## Training/reading list
We have summarized some useful links and resources covering different steps of preclinical systematic review in our [CAMARADES Berlin wiki](http://camarades.de/). To get a detailed overview of the systematic review method, we recommend attending one of our Introduction to SR&MA of Animal Studies workshop which we run several times per year, or if no workshop is happening anytime soon, we recommend going over the materials at your own pace using our eLearning course. All info on signing up for either is available in the CAMARADES Berlin wiki. Project specific literature that you should get yourself familiar with can be found in sharepoint in the respective project's folder. Also check out an extensive list of recommended resources from [CAMARADES Edinburgh](https://camaradesuk.github.io/camarades_cookbook/key-resources.html#training-reading-list). 
